-- Generated by the SCRI footprint editor.
return {
    image = "assets/images/footprint_loader/6WIFV.png",
    color = { 0.96470588, 0.78823529, 0.22352941, 1.00000000 },
    image_transform = {
        x_hex = 0.01533858,
        y_hex = -0.46226691,
        scale_per_hex = 0.03123062,
    },
    footprint = {
        { q = -1, r = -1 },
        { q = 0, r = -1 },
        { q = 1, r = -1 },
        { q = 2, r = -1 },
        { q = -2, r = 0 },
        { q = -1, r = 0 },
        { q = 0, r = 0 },
        { q = 1, r = 0 },
        { q = 2, r = 0 },
        { q = -2, r = 1 },
        { q = -1, r = 1 },
        { q = 0, r = 1 },
        { q = 1, r = 1 },
    },
}
